// langs/en.js — English language pack (ES module)
export const pack = {
    name: 'English',
    nativeName: 'English',
    dir: 'ltr',
    voiceFilter: 'en',

    ui: {
      // Strip
      stripPlaceholder: 'Tap cards to build a sentence',

      // Settings
      settingsTitle: 'Settings',
      sectionGeneral: 'General',
      sectionLanguage: 'Language',
      sectionVoice: 'Voice',
      sectionAi: 'AI Assist',
      labelSound: 'Sound on tap',
      labelShowLabels: 'Show labels',
      labelAnimations: 'Animations',
      labelHighContrast: 'High contrast',
      labelGridSize: 'Grid size',
      gridLarge: 'Large',
      gridMedium: 'Medium',
      gridSmall: 'Small',
      labelLanguage: 'Language',
      labelVoiceEngine: 'Voice engine',
      voiceEngineBrowser: 'Browser',
      labelVoice: 'Voice',
      labelSpeed: 'Speed',
      testVoice: 'Test voice',
      testVoicePhrase: 'Hello, this is my voice',
      labelSmartSentences: 'Smart sentences',
      labelWordHints: 'Word hints',
      voiceDefault: 'Default',

      // Search
      searchPlaceholder: 'Search...',
      searchNoMatches: 'No matches',

      // Modal
      newCard: 'New Card',
      editCard: 'Edit Card',
      newDeck: 'New Deck',
      editDeck: 'Edit Deck',
      newBinder: 'New Binder',
      editBinder: 'Edit Binder',
      editProfile: 'Edit Profile',
      modalLabel: 'Label',
      modalDecksToInclude: 'Decks to include',
      modalPlaceholderBinder: 'e.g. school',
      modalPlaceholderDeck: 'e.g. animals',
      modalPlaceholderCard: 'e.g. dog',
      modalPlaceholderProfile: 'e.g. david',
      btnCancel: 'Cancel',
      btnSave: 'Save',
      btnDelete: 'Delete',
      btnEmoji: 'Emoji',
      btnCamera: 'Camera',
      btnGallery: 'Gallery',
      btnSymbols: 'Symbols',
      emojiPlaceholder: 'Type or paste an emoji...',
      symbolPlaceholder: 'Search symbols...',
      symbolSearching: 'Searching...',
      symbolNoResults: 'No symbols found',
      symbolSearchFailed: 'Search failed',

      // Misc
      cardCount: function (n) { return n + ' cards'; },
      profilePlaceholder: 'New profile...',
      confirmDeleteProfile: function (name) { return 'Delete profile "' + name + '"?'; },
      modeUser: 'User',
      modeCaretaker: 'Caretaker',
      profileDefault: 'Default',
      cameraError: 'Could not access camera.',

      // Reports
      sectionReports: 'Reports',
      labelViewReports: 'Usage reports',
      btnViewReports: 'View',
      reportsTitle: 'Reports',
      reportToday: 'Today',
      reportWeek: 'This Week',
      reportMonth: 'This Month',
      reportWordsUsed: 'Words used',
      reportSentences: 'Sentences',
      reportTopWord: 'Top word',
      reportSessionTime: 'Session time',
      reportTopWords: 'Top Words',
      reportTopDecks: 'Top Decks',
      reportAiUsage: 'AI Assist',
      reportSmartSentences: 'Smart sentences used',
      reportSuggestionsUsed: 'Suggestions tapped',
      reportNoData: 'No data yet',

      // Help
      sectionHelp: 'Help',
      labelTutorial: 'App tutorial',
      btnShowTutorial: 'Show',

      // Tutorial
      tutStep1: 'These are your card decks. Tap a deck to see the cards inside.',
      tutStep2: 'Cards you tap appear here to build a sentence.',
      tutStep3: 'Press this button to speak your sentence out loud.',
      tutStep4: 'Word suggestions appear here to help you build sentences faster.',
      tutStep5: 'Switch profiles and toggle between User and Caretaker mode here.',
      tutStep6: 'Use binders to organize your decks into groups.',
      tutNext: 'Next',
      tutDone: 'Got it!',

      // Update toast
      updateAvailable: 'New version available — tap to update'
    },

    aiPrompt: 'You are an AAC communication assistant. The user built this sequence of words by tapping picture cards: [WORDS]. Suggest ONE short, natural sentence that captures their intent. Reply with ONLY the sentence, nothing else.',

    suggestions: {
      // Sentence starters
      '': ['I', 'want', 'go', 'help'],
      // People / Pronouns
      'i': ['want', 'go', 'like', 'see'],
      'you': ['want', 'go', 'help', 'like'],
      'mom': ['help', 'want', 'go', 'please'],
      'dad': ['help', 'want', 'go', 'please'],
      'friend': ['want', 'play', 'go', 'help'],
      'sister': ['help', 'play', 'want', 'stop'],
      'brother': ['help', 'play', 'want', 'stop'],
      'baby': ['help', 'want', 'sleep', 'eat'],
      'teacher': ['help', 'please', 'want', 'see'],
      'doctor': ['help', 'please', 'pain', 'medicine'],
      'grandpa': ['help', 'go', 'want', 'please'],
      'grandma': ['help', 'go', 'want', 'please'],
      'everyone': ['hi', 'bye', 'help', 'please'],
      // Actions — expanded with places, time, people
      'want': ['eat', 'drink', 'play', 'go'],
      'go': ['school', 'park', 'home', "grandma's"],
      'do': ['more', 'good', 'help', 'now'],
      'eat': ['food', 'more', 'now', 'please'],
      'drink': ['water', 'more', 'now', 'please'],
      'help': ['please', 'mom', 'dad', 'now'],
      'stop': ['please', 'no', 'now', 'wait'],
      'play': ['outside', 'park', 'toy', 'more'],
      'sleep': ['tired', 'now', 'please', 'want'],
      'see': ['that is', 'here', 'there', 'wow'],
      // Past tense (narrative support)
      'went': ['school', 'park', "grandma's", 'store'],
      'played': ['outside', 'park', 'toy', 'friend'],
      'ate': ['food', 'a lot', 'more', 'good'],
      'fell': ['down', 'pain', 'help', 'mom'],
      'cried': ['sad', 'help', 'mom', 'dad'],
      // Feelings / States
      'happy': ['play', 'more', 'thank you', 'wow'],
      'sad': ['help', 'want', 'mom', 'dad'],
      'angry': ['stop', 'help', 'want', 'no'],
      'scared': ['help', 'mom', 'dad', 'scary'],
      'tired': ['sleep', 'help', 'want', 'now'],
      'pain': ['help', 'medicine', 'doctor', 'mom'],
      'like': ['food', 'play', 'more', 'it is'],
      "don't like": ['stop', 'no', 'help', 'scary'],
      // Descriptors
      'more': ['please', 'want', 'food', 'water'],
      'less': ['please', 'want', 'good'],
      'a lot': ['more', 'want', 'good'],
      'a little': ['more', 'want', 'please'],
      'good': ['more', 'yes', 'thank you', 'happy'],
      'bad': ['help', 'stop', 'no', 'want'],
      'here': ['please', 'want', 'help', 'now'],
      'there': ['go', 'want', 'see', 'please'],
      // Things / Needs — expanded with descriptors
      'water': ['please', 'more', 'cold', 'hot'],
      'food': ['please', 'more', 'hot', 'good'],
      'bathroom': ['please', 'go', 'now', 'help'],
      'toy': ['please', 'play', 'new', 'big'],
      'phone': ['please', 'want', 'now', 'mine'],
      'medicine': ['please', 'help', 'now', 'pain'],
      'clothes': ['please', 'help', 'new', 'want'],
      // Social / Pragmatic
      'hi': ['mom', 'dad', 'friend', 'everyone'],
      'bye': ['mom', 'dad', 'friend', 'everyone'],
      'please': ['help', 'more', 'now', 'thank you'],
      'thank you': ['bye', 'more', 'yes', 'happy'],
      'yes': ['please', 'want', 'more', 'go'],
      'no': ['stop', 'want', "don't like", 'help'],
      'wait': ['please', 'help', 'want'],
      "let's": ['go', 'play', 'eat', 'do'],
      // Multi-word sequences — expanded
      'i want': ['eat', 'drink', 'play', 'go'],
      'i go': ['school', 'park', 'home', "grandma's"],
      'i like': ['food', 'play', 'toy', 'it is'],
      'i see': ['big', 'funny', 'scary', 'nice'],
      'i think': ['yes', 'no', 'good', 'funny'],
      'i feel': ['happy', 'sad', 'scared', 'tired'],
      'you want': ['play', 'eat', 'go', 'help'],
      'want eat': ['food', 'now', 'please', 'more'],
      'want drink': ['water', 'now', 'please', 'more'],
      'want play': ['outside', 'park', 'toy', 'now'],
      'want go': ['school', 'park', 'home', "grandma's"],
      'want help': ['please', 'now', 'mom', 'dad'],
      'go school': ['tomorrow', 'today', 'now', 'please'],
      'go park': ['now', 'tomorrow', 'please', 'want'],
      'go home': ['now', 'please', 'want', 'tired'],
      // Questions
      'where': ['go', 'school', 'park', 'home'],
      'when': ['go', 'eat', 'play', 'tomorrow'],
      'how': ['do', 'help', 'go', 'please'],
      'what': ['want', 'do', 'it is', 'that is'],
      'why': ['stop', 'go', 'sad', 'scared'],
      'who': ['help', 'want', 'go', 'friend'],
      'with whom': ['go', 'play', 'eat', 'mom'],
      // Descriptions — expanded with new adjectives
      'big': ['more', 'a lot', 'good', 'wow'],
      'small': ['a little', 'less', 'good', 'nice'],
      'hot': ['water', 'food', 'help', 'stop'],
      'cold': ['water', 'clothes', 'help', 'want'],
      'up': ['go', 'help', 'please', 'now'],
      'down': ['go', 'help', 'please', 'stop'],
      'new': ['want', 'good', 'more', 'pretty'],
      'old': ['stop', 'want', 'bad', 'help'],
      'fast': ['go', 'more', 'wow', 'help'],
      'slow': ['please', 'help', 'stop', 'wait'],
      'nice': ['more', 'thank you', 'yes', 'like'],
      'sick': ['help', 'medicine', 'doctor', 'mom'],
      'red': ['big', 'small', 'pretty', 'want'],
      'blue': ['big', 'small', 'pretty', 'want'],
      'yellow': ['big', 'small', 'pretty', 'want'],
      'pretty': ['more', 'wow', 'like', 'want'],
      'soft': ['nice', 'like', 'want', 'good'],
      'hard': ['help', 'stop', 'bad', 'want'],
      // Comments / Pragmatic starters
      'i see': ['big', 'funny', 'scary', 'nice'],
      'i think': ['yes', 'no', 'good', 'funny'],
      'i feel': ['happy', 'sad', 'scared', 'tired'],
      'it is': ['big', 'hot', 'cold', 'broken'],
      'that is': ['funny', 'scary', 'mine', 'nice'],
      'wow': ['big', 'pretty', 'funny', 'good'],
      'funny': ['wow', 'more', 'like', 'happy'],
      'mine': ['please', 'stop', 'want', 'no'],
      'broken': ['help', 'sad', 'want', 'new'],
      'scary': ['help', 'mom', 'stop', 'scared'],
      // Places
      'school': ['go', 'tomorrow', 'today', 'fun'],
      'park': ['go', 'play', 'today', 'fun'],
      'home': ['go', 'now', 'want', 'mom'],
      "grandma's": ['go', 'tomorrow', 'want', 'fun'],
      'outside': ['go', 'play', 'now', 'want'],
      'inside': ['go', 'play', 'now', 'want'],
      'car': ['go', 'want', 'now', 'please'],
      'store': ['go', 'want', 'please', 'mom'],
      // Time / Narrative
      'today': ['go', 'play', 'eat', 'want'],
      'tomorrow': ['go', 'school', 'play', 'want'],
      'yesterday': ['went', 'played', 'ate', 'was'],
      'first': ['eat', 'go', 'play', 'want'],
      'next': ['go', 'eat', 'play', 'do'],
      'after': ['eat', 'play', 'go', 'sleep'],
      'finally': ['go', 'eat', 'play', 'home'],
      'now': ['want', 'go', 'help', 'please'],
      // Connectors / Narrative
      'and': ['then', 'want', 'go', 'play'],
      'but': ['want', 'no', 'help', 'stop'],
      'because': ['want', 'like', 'happy', 'sad'],
      'then': ['go', 'eat', 'play', 'sleep']
    },

    defaults: {
      decks: {
        people: { hex: '#F5C518', i: '👤', w: [{ e: '🙋', l: 'I' }, { e: '👤', l: 'you' }, { e: '👩', l: 'mom' }, { e: '👨', l: 'dad' }, { e: '👧', l: 'sister' }, { e: '👦', l: 'brother' }, { e: '👶', l: 'baby' }, { e: '👫', l: 'friend' }, { e: '🧑‍🏫', l: 'teacher' }, { e: '👨‍⚕️', l: 'doctor' }, { e: '👴', l: 'grandpa' }, { e: '👵', l: 'grandma' }, { e: '👥', l: 'everyone' }] },
        actions: { hex: '#6BAF7B', i: '🏃', w: [{ e: '🤲', l: 'want' }, { e: '🚶', l: 'go' }, { e: '✊', l: 'do' }, { e: '🍽️', l: 'eat' }, { e: '🥤', l: 'drink' }, { e: '🤝', l: 'help' }, { e: '🛑', l: 'stop' }, { e: '🎮', l: 'play' }, { e: '💤', l: 'sleep' }, { e: '👀', l: 'see' }, { e: '🚶‍♂️', l: 'went' }, { e: '🎯', l: 'played' }, { e: '🍴', l: 'ate' }, { e: '🤸', l: 'fell' }, { e: '😭', l: 'cried' }] },
        feelings: { hex: '#6B9DC7', i: '❤️', w: [{ e: '😊', l: 'happy' }, { e: '😢', l: 'sad' }, { e: '😠', l: 'angry' }, { e: '😰', l: 'scared' }, { e: '😴', l: 'tired' }, { e: '🤕', l: 'pain' }, { e: '😍', l: 'like' }, { e: '😤', l: "don't like" }] },
        descriptors: { hex: '#6B9DC7', i: '📏', w: [{ e: '➕', l: 'more' }, { e: '➖', l: 'less' }, { e: '💯', l: 'a lot' }, { e: '🤏', l: 'a little' }, { e: '👍', l: 'good' }, { e: '👎', l: 'bad' }, { e: '📍', l: 'here' }, { e: '👉', l: 'there' }] },
        things: { hex: '#E47A20', i: '⭐', w: [{ e: '💧', l: 'water' }, { e: '🍎', l: 'food' }, { e: '🚽', l: 'bathroom' }, { e: '🧸', l: 'toy' }, { e: '📱', l: 'phone' }, { e: '💊', l: 'medicine' }, { e: '👕', l: 'clothes' }] },
        social: { hex: '#C78DA3', i: '💬', w: [{ e: '👋', l: 'hi' }, { e: '🫡', l: 'bye' }, { e: '🙏', l: 'please' }, { e: '🫶', l: 'thank you' }, { e: '✅', l: 'yes' }, { e: '❌', l: 'no' }, { e: '⏳', l: 'wait' }, { e: '🎉', l: "let's" }, { e: '➡️', l: 'and' }, { e: '🔀', l: 'but' }, { e: '💡', l: 'because' }, { e: '⏭️', l: 'then' }] },
        questions: { hex: '#5BA4CF', i: '❓', w: [{ e: '📍', l: 'where' }, { e: '🕐', l: 'when' }, { e: '🤔', l: 'how' }, { e: '❓', l: 'what' }, { e: '🤷', l: 'why' }, { e: '👤', l: 'who' }, { e: '👥', l: 'with whom' }] },
        descriptions: { hex: '#E8A838', i: '🎨', w: [{ e: '🔴', l: 'big' }, { e: '🔵', l: 'small' }, { e: '🔥', l: 'hot' }, { e: '🧊', l: 'cold' }, { e: '⬆️', l: 'up' }, { e: '⬇️', l: 'down' }, { e: '🆕', l: 'new' }, { e: '🕰️', l: 'old' }, { e: '⚡', l: 'fast' }, { e: '🐢', l: 'slow' }, { e: '😊', l: 'nice' }, { e: '😷', l: 'sick' }, { e: '🟥', l: 'red' }, { e: '🟦', l: 'blue' }, { e: '🟡', l: 'yellow' }, { e: '🌸', l: 'pretty' }, { e: '🧸', l: 'soft' }, { e: '🪨', l: 'hard' }] },
        places: { hex: '#4ABFA5', i: '📍', w: [{ e: '🏫', l: 'school' }, { e: '🏡', l: 'home' }, { e: '🌳', l: 'park' }, { e: '👵', l: "grandma's" }, { e: '🌞', l: 'outside' }, { e: '🏠', l: 'inside' }, { e: '🚗', l: 'car' }, { e: '🏪', l: 'store' }] },
        comments: { hex: '#E87CA0', i: '💭', w: [{ e: '👁️', l: 'I see' }, { e: '🧠', l: 'I think' }, { e: '💗', l: 'I feel' }, { e: '👆', l: 'it is' }, { e: '👉', l: 'that is' }, { e: '🤩', l: 'wow' }, { e: '😂', l: 'funny' }, { e: '🙋', l: 'mine' }, { e: '💔', l: 'broken' }, { e: '😨', l: 'scary' }] },
        time: { hex: '#7B8EC2', i: '🕐', w: [{ e: '📅', l: 'today' }, { e: '🌅', l: 'tomorrow' }, { e: '⏪', l: 'yesterday' }, { e: '1️⃣', l: 'first' }, { e: '⏭️', l: 'next' }, { e: '⏩', l: 'after' }, { e: '🏁', l: 'finally' }, { e: '⏰', l: 'now' }] },
        phrases: { hex: '#9B7DC7', i: '💜', w: [] }
      },
      binders: {
        all: { icon: '📋', decks: null },
        school: { icon: '🎓', decks: ['people', 'actions', 'social', 'questions', 'places', 'time', 'comments'] },
        home: { icon: '🏠', decks: ['people', 'feelings', 'things', 'descriptors', 'descriptions', 'places', 'comments'] },
        mealtime: { icon: '🍽️', decks: ['people', 'actions', 'things', 'descriptors', 'descriptions', 'social', 'comments'] },
        playground: { icon: '🛝', decks: ['people', 'actions', 'feelings', 'places', 'social', 'comments', 'descriptions'] },
        therapy: { icon: '🧩', decks: ['people', 'actions', 'feelings', 'comments', 'time', 'questions', 'descriptions'] }
      }
    }
};
